VST/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('accounts/', include('allauth.urls')),
    #path('', include('admin_panel.urls')),
    #path('', include('authentication.urls')),
    #path('', include('survey.urls')),
]

if settings. DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

urlpatterns = [
    path('', views.home_page, name='home'),
    path('services/', views.services_page, name='services'),
    path('events/', views.events_page, name='events'),
    path('events/<int:event_id>/', views.event_detail_view, name='event-detail'),
    path('contacts/', views.contacts_page, name='contacts'),
    path('feedback/', views.feedback, name='feedback'),

    path('register/', views.user_register, name='user-register'),
    path('login/', views.user_login, name='user-login'),  # Ensure this matches LOGIN_URL
    path('logout/', auth_views.LogoutView.as_view(next_page='home'), name='logout'),

    path('admin-register/', views.admin_register, name='admin-register'),
    path('admin-login/', views.admin_login, name='admin-login'),
    path('admin-panel/', views.admin_panel, name='admin-panel'),
    path('admin-panel/carousel-images/', views.admin_panel_carousel_images, name='admin-panel-carousel-images'),
    path('admin-panel/more-events/', views.admin_panel_more_events, name='admin-panel-more-events'),
    path('admin-register/verify-email/', views.verify_email, name='verify-email'),

    path('password-reset/', views.password_reset_request, name='password-reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='main/pages/password-reset/password_reset_done.html'), name='password-reset-done'),
    path('reset/<uidb64>/<token>/', views.password_reset_confirm, name='password-reset-confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='main/pages/password-reset/password_reset_complete.html'), name='password-reset-complete'),
    path('reset/invalid/', auth_views.PasswordResetConfirmView.as_view(template_name='main/pages/password-reset/password_reset_invalid.html'), name='password-reset-invalid'),

    path('admin-panel/more-events/add-event/', views.add_event, name='add-event'),
    path('admin-panel/more-events/update-event/<int:event_id>/', views.update_event, name='update-event'),
    path('admin-panel/more-events/delete-event/<int:event_id>/', views.delete_event, name='delete-event'),

    path('admin-panel/carousel-images/add-upcoming-events/', views.add_carousel_image, name='add-carousel-image'),
    path('admin-panel/carousel-images/update-upcoming-events/<int:image_id>/', views.update_carousel_image, name='update-upcoming-event'),
    path('admin-panel/carousel-images/delete-upcoming-events/<int:image_id>/', views.delete_carousel_image, name='delete-upcoming-event'),

    path('admin-panel/add-question/', views.add_question, name='add-question'),
    path('admin-panel/update-question/<int:question_id>/', views.update_question, name='update-question'),
    path('admin-panel/delete-question/<int:question_id>/', views.delete_question, name='delete-question'),
    path('admin-panel/delete-response/<int:user_id>/', views.delete_response, name='delete-response'),
    path('admin-panel/delete-all-responses/', views.delete_all_responses, name='delete-all-responses'),
    path('admin-panel/export-responses/', views.export_responses, name='export-responses'),
]

admin_panel/models.py
from django.db import models

# Create your models here.

main/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone
from datetime import timedelta
from django.conf import settings


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        return self.create_user(email, password, **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(unique=True)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_admin_user = models.BooleanField(default=False)
    verification_code = models.CharField(max_length=6, blank=True, null=True)
    verification_code_expiration = models.DateTimeField(blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Event(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    thumbnail = models.ImageField(upload_to='event_thumbnails/')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

class EventImage(models.Model):
    event = models.ForeignKey(Event, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='event_images/', null=True, blank=True)

    def __str__(self):
        return f"Image for {self.event.title}"
    
class UpcomingEventsCarouselImage(models.Model):
    image = models.ImageField(upload_to='carousel_images/')
    caption = models.CharField(max_length=255, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Carousel Image {self.id}"

class Question(models.Model):
    QUESTION_TYPES = [
        ('text', 'Text'),
        ('radio', 'Radio Button'),
        ('rating_1_5', 'Rating 1-5'),
        ('rating_1_10', 'Rating 1-10'),
    ]
    text = models.CharField(max_length=200)
    question_type = models.CharField(max_length=50, choices=QUESTION_TYPES, default='text')
    radio_choices = models.CharField(max_length=200, blank=True, help_text='Comma-separated choices for radio buttons')

    def __str__(self):
        return self.text

class Response(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='responses', on_delete=models.SET_NULL, null=True, blank=True)
    question = models.ForeignKey(Question, related_name='responses', on_delete=models.CASCADE)
    text = models.TextField()
    submitted_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text

admin_panel/views.py
from django.shortcuts import render

# Create your views here.

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .decorators import login_required, admin_required
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm
from django.contrib.auth.tokens import default_token_generator
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_str
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.contrib import messages

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, PatternFill, Border, Side
from datetime import datetime
import csv

from django.contrib.auth import login, authenticate
from django.urls import reverse
from django.forms import modelformset_factory
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LogoutView
from django.views import View
from .models import *
from .forms import *
from django.http import HttpResponse
import logging
from collections import OrderedDict

# Logger setup
logger = logging.getLogger(__name__)

User = get_user_model()

def home_page(request):
    carousel_images = UpcomingEventsCarouselImage.objects.all()
    return render (request, 'main/pages/home.html', {'carousel_images': carousel_images})

def services_page(request):
    return render (request, 'main/pages/services.html')

def events_page(request):
    events = Event.objects.all()
    return render(request, 'main/pages/events.html', {'events': events})

def event_detail_view(request, event_id):
    event = get_object_or_404(Event, pk=event_id)
    return render(request, 'main/pages/event_detail.html', {'event': event})

def contacts_page(request):
    return render (request, 'main/pages/contacts.html')


def admin_register(request):
    if request.method == 'POST':
        form = AdminRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Inactivate account until verified
            user.verification_code = get_random_string(length=6, allowed_chars='0123456789')
            user.verification_code_expiration = timezone.now() + timedelta(hours=1)
            user.save()
            send_verification_email(user)
            request.session['pending_user_id'] = user.id
            return redirect('verify-email')
    else:
        form = AdminRegistrationForm()
    return render(request, 'main/pages/registration-pages/admin_register.html', {'form': form})

def send_verification_email(user):
    verification_code = user.verification_code
    user.save()
    
    send_mail(
        'Your Verification Code',
        f'Your verification code is {verification_code}.',
        'noreply@vstlivestockcorporation.net',
        [user.email],
        fail_silently=False,
    )

def verify_email(request):
    user_id = request.session.get('pending_user_id')
    user = get_object_or_404(CustomUser, id=user_id)

    if request.method == 'POST':
        form = VerificationForm(request.POST)
        if 'resend_code' in request.POST:
            user.verification_code = get_random_string(length=6, allowed_chars='0123456789')
            user.verification_code_expiration = timezone.now() + timedelta(hours=1)
            user.save()
            send_verification_email(user)
            return render(request, 'main/pages/registration-pages/verify_email.html', {'form': form, 'message': 'New verification code sent to your email.'})
        elif 'cancel' in request.POST:
            user.delete()
            return redirect('home')
        else:
            if form.is_valid():
                if user.verification_code == form.cleaned_data['code'] and user.verification_code_expiration > timezone.now():
                    user.is_active = True
                    user.save()
                    login(request, user)
                    return redirect('admin-login')
                else:
                    form.add_error('code', 'Invalid or expired verification code.')
    else:
        form = VerificationForm()
    return render(request, 'main/pages/registration-pages/verify_email.html', {'form': form})



def user_register(request):
    next_url = request.GET.get('next', reverse('user-login'))
    if request.method == 'POST':
        form = UserRegistrationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return redirect(next_url)
    else:
        form = UserRegistrationForm()
    return render(request, 'main/pages/registration-pages/user_register.html', {'form': form, 'next': next_url})


# Admin Login View
def admin_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')  # Using email instead of username
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None and user.is_admin_user:
                login(request, user)
                return redirect('admin-panel')
            else:
                form.add_error(None, "Invalid credentials or not an admin user")
    else:
        form = AuthenticationForm()
    return render(request, 'main/pages/login-pages/admin_login.html', {'form': form})

# User Login View
def user_login(request):
    next_url = request.GET.get('next', reverse('feedback'))
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('username')  # Using email instead of username
            password = form.cleaned_data.get('password')
            user = authenticate(request, email=email, password=password)
            if user is not None:
                login(request, user)
                return redirect(next_url)
            else:
                form.add_error(None, "Invalid credentials")
    else:
        form = AuthenticationForm()
    return render(request, 'main/pages/login-pages/user_login.html', {'form': form, 'next': next_url})

def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            email = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(email=email)
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "main/pages/password-reset/password_reset_email.txt"
                    c = {
                        "email": user.email,
                        'domain': get_current_site(request).domain,
                        'site_name': 'Your site name',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'http',
                    }
                    email = render_to_string(email_template_name, c)
                    send_mail(subject, email, 'noreply@vstlivestockcorporation.net', [user.email], fail_silently=False)
            return redirect("password-reset-done")
    password_reset_form = PasswordResetForm()
    return render(request=request, template_name="main/pages/password-reset/password_reset.html", context={"password_reset_form": password_reset_form})

def password_reset_confirm(request, uidb64=None, token=None):
    UserModel = get_user_model()
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = UserModel.objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError, UserModel.DoesNotExist):
        user = None

    if user is not None and default_token_generator.check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                messages.success(request, 'Your password has been successfully reset.')
                return redirect('password-reset-complete')
        else:
            form = SetPasswordForm(user)
        return render(request, 'main/pages/password-reset/password_reset_confirm.html', {'form': form})
    else:
        messages.error(request, 'The password reset link is invalid, possibly because it has already been used. Please request a new password reset.')
        return redirect('password-reset')


logger = logging.getLogger(__name__)

# Admin Panel View
@admin_required(login_url='admin-login')
def admin_panel(request):
    questions = Question.objects.all()
    all_responses = Response.objects.select_related('user', 'question').all()
    
    user_responses = {}
    for response in all_responses:
        user = response.user
        if user not in user_responses:
            user_responses[user] = {}
        user_responses[user][response.question.id] = response

    total_users_responded = len(user_responses)

    recent_responses = all_responses.order_by('-submitted_at')
    recent_users = OrderedDict()
    for response in recent_responses:
        if response.user not in recent_users:
            recent_users[response.user] = response
        if len(recent_users) >= 1:
            break
    recent_responses = list(recent_users.values())

    for user, user_responses_dict in user_responses.items():
        logger.debug(f'User: {user.email}, Responses: {user_responses_dict}')
    
    context = {
        'user': request.user,
        'questions': questions,
        'total_responses': total_users_responded,
        'recent_responses': recent_responses,

main/templates/main/pages/admin-pages/admin_navbar.html
{% load static %}
<nav class="admin-navbar">
    <div class="admin-navbar-logo">
        <a class="admin-navbar-logo-link" href="{% url 'admin-panel' %}">
            Admin Panel
        </a>
    </div>

    <!-- Navbar Menu Items -->
    <div class="admin-navbar-right">
        <ul>
            <li><a href="{% url 'admin-panel' %}">Home / Survey</a></li>
            <li><a href="{% url 'admin-panel-carousel-images' %}">Carousel Images</a></li>
            <li><a href="{% url 'admin-panel-more-events' %}">More Events</a></li>
        </ul>
    </div>

    <!-- Burger Menu for Small Screens -->
    <div class="admin-burger" id="admin-burger">
        <div class="admin-line1"></div>
        <div class="admin-line2"></div>
        <div class="admin-line3"></div>
    </div>
</nav>

<script>
    // For Admin Nav Bar Responsive Burger
    const adminBurger = document.getElementById('admin-burger');
    const adminNavbarRight = document.querySelector('.admin-navbar-right');

    adminBurger.addEventListener('click', () => {
        adminNavbarRight.classList.toggle('active');
    });
</script>

main/templates/main/pages/admin-pages/admin_panel.html
{% extends 'main/pages/index.html' %}
{% load static %}
{% load custom_tags %}
{% load tz %}

{% block content %}
    {% include 'main/pages/admin-pages/admin_navbar.html' %}

<div id="section-admin-panel" class="admin-panel">
    <h1>Admin Panel</h1>

    <div class="summary-cards">
        <div class="card">
            <p>{{ total_responses }}</p>
            <h3>Total Responses:</h3>
        </div>
        <div class="card">
            <ul>
                {% for response in recent_responses %}
                    <li>
                        <p class="email">{{ response.user.email }}</p>
                    </li>
                {% endfor %}
            </ul>
            <h3 class="card-title">Recent Responses:</h3>
        </div>
    </div>
    
    <div class="mb-3">
        <a href="{% url 'export-responses' %}" class="export-responses-btn">Export to Excel</a>
    </div>

<!-- New section for responses (Vertical Layout with Blue Questions and Bottom Delete Button) -->
<div id="section-responses" class="table-section mt-5">
    <div class="section-header">
        <h2>Responses</h2>
        <a href="{% url 'delete-all-responses' %}" class="delete-all-responses-btn">Delete All Responses</a>
    </div>
    <div class="admin-table-wrapper">
        <div class="table-responsive">
            <table class="admin-responses-table"> <!-- Use a unique class for the responses table -->
                <thead>
                    <tr>
                        <th>Email:</th>
                        {% for user in user_responses.keys %}
                            <th>{{ user.email }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for question in questions %}
                        <tr>
                            <td class="question-column">{{ question.text }}</td>
                            {% for user, responses in user_responses.items %}
                                <td>
                                    {% with response=responses|get_item:question.id %}
                                        {{ response.text|default:"-" }}
                                    {% endwith %}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    <tr>
                        <td class="actions-column">Actions</td>
                        {% for user in user_responses.keys %}
                            <td>
                                <a href="{% url 'delete-response' user.id %}" class="delete-response-btn">Delete</a>
                            </td>
                        {% endfor %}
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>


    <div class="mb-3">
        <a href="{% url 'add-question' %}" class="add-question-btn">Add Question</a>
    </div>

    <div id="section-questions" class="table-section">
        <div class="section-header">
            <h2>Questions</h2>
        </div>
        <div class="admin-table-wrapper">
            <div class="table-responsive">
                <table class="admin-table">
                    <thead>
                        <tr>
                            <th>Question ID</th>
                            <th>Question Text</th>
                            <th>Question Type</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for question in questions %}
                            <tr>
                                <td>{{ question.id }}</td>
                                <td>{{ question.text }}</td>
                                <td>{{ question.get_question_type_display }}</td>
                                <td>
                                    <div class="admin-dropdown">
                                        <button class="admin-dropdown-toggle" type="button" onclick="toggleAdminDropdown({{ question.id }})">
                                            &#9776;
                                        </button>
                                        <ul class="admin-dropdown-menu" id="admin-dropdown-{{ question.id }}">
                                            <li><a class="admin-dropdown-item" href="{% url 'update-question' question.id %}">Edit</a></li>
                                            <li><a class="admin-dropdown-item text-danger" href="{% url 'delete-question' question.id %}">Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<script>
    function toggleAdminDropdown(id) {
        var dropdown = document.getElementById('admin-dropdown-' + id);
        dropdown.classList.toggle('show');
    }

    window.onclick = function(event) {
        if (!event.target.matches('.admin-dropdown-toggle')) {
            var dropdowns = document.getElementsByClassName("admin-dropdown-menu");
            for (var i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }

    document.querySelectorAll('.admin-dropdown-menu').forEach(dropdown => {
        dropdown.addEventListener('mouseleave', function() {
            dropdown.classList.remove('show');
        });
    });
</script>

{% endblock %}

main/templates/main/pages/admin-pages/admin_panel_carousel_images.html
{% extends 'main/pages/index.html' %}
{% load static %}

{% block content %}

    {% include 'main/pages/admin-pages/admin_navbar.html' %}
<!-- Admin Panel Section -->
<div id="section-admin-panel" class="admin-panel">
    <h1>Admin Panel</h1>

    <div class="summary-cards">
        <div class="card">
            <p>{{ total_images }}</p>
            <h3 class="card-title">Images Total:</h3>
        </div>
        <div class="card">
            <p>{{ recent_caption }}</p>
            <h3 class="card-title">Recently Added Image:</h3>
        </div>
    </div>

    <div id="section-upcoming-events" class="table-section">
        <div class="section-header">
            <h2>Upcoming Events</h2>
            <a href="{% url 'add-carousel-image' %}" class="add-button">Add</a>
        </div>
        <div class="admin-table-wrapper">
            <div class="table-responsive">
                <table class="admin-table">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Caption</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for image in carousel_images %}
                            <tr>
                                <td>
                                    <img src="{{ image.image.url }}" class="profile-picture" alt="Carousel Image">
                                </td>
                                <td>{{ image.caption }}</td>
                                <td>
                                    <div class="admin-dropdown">
                                        <button class="admin-dropdown-toggle" type="button" onclick="toggleAdminDropdown({{ image.id }})">
                                            &#9776;
                                        </button>
                                        <ul class="admin-dropdown-menu" id="admin-dropdown-{{ image.id }}">
                                            <li><a class="admin-dropdown-item" href="{% url 'update-upcoming-event' image.id %}">Edit</a></li>
                                            <li><a class="admin-dropdown-item text-danger" href="{% url 'delete-upcoming-event' image.id %}">Delete</a></li>
                                        </ul>
                                    </div>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>


<!-- Add this script to handle the dropdown toggling -->
<script>
    function toggleAdminDropdown(id) {
        var dropdown = document.getElementById('admin-dropdown-' + id);
        dropdown.classList.toggle('show');
    }

    // Close the dropdown if the user clicks outside of it or if the mouse leaves the dropdown
    window.onclick = function(event) {
        if (!event.target.matches('.admin-dropdown-toggle')) {
            var dropdowns = document.getElementsByClassName("admin-dropdown-menu");
            for (var i = 0; i < dropdowns.length; i++) {
                var openDropdown = dropdowns[i];
                if (openDropdown.classList.contains('show')) {
                    openDropdown.classList.remove('show');
                }
            }
        }
    }

    document.querySelectorAll('.admin-dropdown-menu').forEach(dropdown => {
        dropdown.addEventListener('mouseleave', function() {
            dropdown.classList.remove('show');
        });
    });
</script>

{% endblock %}